name: Check Resources
on: [pull_request, push]

jobs:
  check_resources:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - run: ./gradlew runDatagen --stacktrace --warning-mode=fail
      - run: if [ -n "$(git status --porcelain)" ]; then exit 1; fi