name: Crowdin Download

on: [ workflow_dispatch ]

permissions:
  contents: write
  pull-requests: write

jobs:
  crowdin:
    strategy:
      matrix:
        minecraft-version: [
          1.21.1,
          1.21.4
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true

          crowdin_branch_name: ${{ env.BRANCH_NAME }}
          localization_branch_name: ${{ matrix.minecraft-version }}-translate/l10n-crowdin-translations

          create_pull_request: true
          pull_request_title: '[${{ matrix.minecraft-version }}] New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_base_branch_name: ${{ matrix.minecraft-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}